<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="180139" started-at="2018-11-21T10:20:40Z" finished-at="2018-11-21T10:23:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="180139" started-at="2018-11-21T10:20:40Z" finished-at="2018-11-21T10:23:40Z">
      <class name="sanity.PrivatePractitionerTestCase">
        <test-method status="PASS" signature="testdata()[pri:0, instance:sanity.PrivatePractitionerTestCase@2c78d320]" name="testdata" is-config="true" duration-ms="16" started-at="2018-11-21T15:50:40Z" finished-at="2018-11-21T15:50:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdata -->
        <test-method status="PASS" signature="initBrowser()[pri:0, instance:sanity.PrivatePractitionerTestCase@2c78d320]" name="initBrowser" is-config="true" duration-ms="8817" started-at="2018-11-21T15:50:40Z" finished-at="2018-11-21T15:50:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initBrowser -->
        <test-method status="PASS" signature="navigatesTo_privatePractitioner()[pri:0, instance:sanity.PrivatePractitionerTestCase@2c78d320]" name="navigatesTo_privatePractitioner" is-config="true" duration-ms="4759" started-at="2018-11-21T15:50:49Z" finished-at="2018-11-21T15:50:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigatesTo_privatePractitioner -->
        <test-method status="FAIL" signature="test_verifyAllCityList()[pri:0, instance:sanity.PrivatePractitionerTestCase@2c78d320]" name="test_verifyAllCityList" duration-ms="166537" started-at="2018-11-21T15:50:54Z" finished-at="2018-11-21T15:53:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1234 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1234 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at pom.PrivatePractitionerPage.verifyCity(PrivatePractitionerPage.java:528)
	at sanity.PrivatePractitionerTestCase.test_verifyAllCityList(PrivatePractitionerTestCase.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_verifyAllCityList -->
        <test-method status="PASS" signature="destroy()[pri:0, instance:sanity.PrivatePractitionerTestCase@2c78d320]" name="destroy" is-config="true" duration-ms="2380" started-at="2018-11-21T15:53:40Z" finished-at="2018-11-21T15:53:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroy -->
      </class> <!-- sanity.PrivatePractitionerTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
